### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by marvinmarnold** [chainrule-labs/homepage#1]

**Comment by cucupac** [comment]
Looks great so far: clean, minimal, and gets the points across. As for "why we're better", here are some thoughts:

**In comparison to manually shorting:**

1. It abstracts away the details of shorting:
    ➣ which saves knowledgable users time
    ➣ allows people who don't know how to short manually to short

2. Isolated positions:
    ➣ makes it simple keep track of for accounting purposes
    ➣ risk is isolated to single positions

**In comparison to shorting using a perpetual contract protocol:**

We need to research this. I add this as I was asked this a couple times in EthDenver. A preliminary approach could be:

1. We can open a position on a perpetual protocol and extract the following information:
     ➣ how much gas did it cost?
     ➣ how much collateral was needed?
     ➣ is there interest that accrues?
     ➣ is risk isolated?

Here's [our current slide](https://docs.google.com/presentation/d/1_q6KvHe9n4JfYGtQlvdUUP2nk6gGPxBy/edit#slide=id.p5) for more on "Why shAave?":

**Comment by marvinmarnold** [comment]
Very helpful, thanks!

**Comment by marvinmarnold** [comment]
> We can open a position on a perpetual protocol and extract the following information:

This is a great idea. Is shAave ready for us to execute the same positions with it?

**Comment by cucupac** [comment]
> This is a great idea. Is shAave ready for us to execute the same positions with it?
The contracts are technically in a state where they can be empirically tested, yes.

We should be able to deploy to a forked mainnet using foundry, and get the numbers we need.

**Comment by marvinmarnold** [comment]
I just published this to shaave.io. It should take an hour or so for the certificates and DNS to propagate. Some notes:

- Preview for now: https://shaave.carrd.co/
- Cover image needs to be improved. Any ideas? Do yall have any graphics skills? I suck. That said, I'm not worried about finalizing the image until branding/name is decided.
- How many hackathons have you all won something at? Need to fill in a number under "Made by the best"
- I'm hiding several sections, like the token and email signup form until we are ready.

**Comment by 0xernesto** [comment]
Cover image:
- I have basic Figma skills. If we get any ideas, I can try to put something together.

For hackathons, it may make sense to say "Our team has won bounties worth over $XX,000 USD at Y Ethereum hackathons." Here is a rough estimate of hackathons Adam and I have been involved in.

- ETH NewYork 2022
    - Polygon - Pool Prize ($100)
- ETH Mexico 2022
    - Superfluid - Best DeFi Project ($2000)
    - Aave - Best Use ($9000 )
- ETH SanFransico 2022
    - ENS — Integration Bounty ($100)
    - XMTP — Pool Prize ($100)
- ETH Waterloo
    - Risc Zero — Best Use of Bonsai ($1000)
- ETH Chicago 2023
    - One Bounty ($2500)
- ETH NewYork 2023: 
    - Project 1 
        - Unlock Protocol — Most Inventive Use ($3,000)
    - Project 2 
        - ETHGlobal Finalist ($5000)
        - Safe - Best Use of Safe{Core} ($ 1000)
- ETH Istanbul 2023
    - Gnosis Chain - EVM Migration Tool Prize ($2000)
    - Arbitrum - Pool Prize ($100)
    - Scroll - Deploy on Scroll ($100)
- ETH Denver 2024
    - Injective ($5000)
    - Linea ($1000)
    - XDC ($1500)
    - Base ($1500)

**Comment by 0xernesto** [comment]
Also, where is the code for this site? Can we change the colors?

**Comment by marvinmarnold** [comment]
- Emails to move to a shared carrd account
- Incorporate recent info
- New brand

**Comment by marvinmarnold** [comment]
Removed the shape from the background, transferred to a shared Carrd account, and tweaked the colors. Waiting on feedback on wording.

**Comment by marvinmarnold** [comment]
On mobile, is it possible to make the images come after the text?

**Comment by marvinmarnold** [comment]
Done moving images on mobile.

**Comment by marvinmarnold** [comment]
Ah just realized this messed up the desktop version.
